import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:rizqmart/core/theme/context_theme.dart';
import 'package:rizqmart/features/auth/domain/entities/payment/saved_card_entity.dart';
import 'package:rizqmart/features/auth/presentation/bloc/payment/saved_cards/saved_cards_bloc.dart';
import 'package:rizqmart/features/auth/presentation/bloc/payment/saved_cards/saved_cards_event.dart';
import 'package:rizqmart/features/auth/presentation/widgets/buttons/reusable_main_button.dart';
import 'package:rizqmart/features/auth/presentation/widgets/extensions/sized_box.dart';
import 'package:rizqmart/features/auth/presentation/widgets/show_toast_actions.dart';
import 'dart:math';

class AddCardPage extends StatefulWidget {
  final String userId;
  const AddCardPage({super.key, required this.userId});

  @override
  State<AddCardPage> createState() => _AddCardPageState();
}

class _AddCardPageState extends State<AddCardPage> {
  final CardEditController _cardEditController = CardEditController();
  final TextEditingController _nameController = TextEditingController();
  bool _isProcessing = false;

  @override
  void dispose() {
    _cardEditController.dispose();
    _nameController.dispose();
    super.dispose();
  }

  Future<void> _saveCard() async {
    if (_nameController.text.isEmpty) {
      showToast(context, 'Please enter card holder name');
      return;
    }
    
    if (!_cardEditController.complete) {
      showToast(context, 'Please enter valid card details');
      return;
    }

    setState(() {
      _isProcessing = true;
    });

    try {
      // 1. Create Payment Method via Stripe
      final paymentMethod = await Stripe.instance.createPaymentMethod(
        params: const PaymentMethodParams.card(
          paymentMethodData: PaymentMethodData(
            billingDetails: BillingDetails(),
          ),
        ),
      );

      // 2. Create Entity
      final cardEntity = SavedCardEntity(
        id: '', // Generated by Firestore
        paymentMethodId: paymentMethod.id,
        last4: paymentMethod.card.last4 ?? '0000',
        brand: paymentMethod.card.brand ?? 'Unknown',
        expiryMonth: paymentMethod.card.expMonth ?? 0,
        expiryYear: paymentMethod.card.expYear ?? 0,
        cardHolderName: _nameController.text,
        cardColor: _generateRandomColor(),
      );

      // 3. Save to Firestore (via Bloc)
      if (mounted) {
        context.read<SavedCardsBloc>().add(AddSavedCardEvent(cardEntity, widget.userId));
        Navigator.pop(context); // Return to list
      }
    } catch (e) {
      if (mounted) {
        showToast(context, 'Failed to add card: ${e.toString()}');
      }
    } finally {
      if (mounted) {
        setState(() {
          _isProcessing = false;
        });
      }
    }
  }

  int _generateRandomColor() {
    final colors = [
      0xFF1A1F71, // Visa Blue
      0xFFEB001B, // Mastercard Red
      0xFF006FCF, // Amex Blue
      0xFF2C3E50, // Dark Slate
      0xFF8E44AD, // Purple
      0xFF27AE60, // Green
    ];
    return colors[Random().nextInt(colors.length)];
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Add New Card'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          children: [
            TextField(
              controller: _nameController,
              decoration: InputDecoration(
                labelText: 'Card Holder Name',
                border: OutlineInputBorder(borderRadius: BorderRadius.circular(12)),
              ),
            ),
            20.h,
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                border: Border.all(color: context.cs.outline),
                borderRadius: BorderRadius.circular(12),
              ),
              child: CardField(
                controller: _cardEditController,
                enablePostalCode: false,
                style: context.isDarkMode
                    ? const TextStyle(color: Colors.white)
                    : const TextStyle(color: Colors.black),
                decoration: InputDecoration(
                  border: InputBorder.none,
                  hintText: 'Card Details',
                  hintStyle: TextStyle(color: context.cs.onSurface.withOpacity(0.5)),
                ),
              ),
            ),
            40.h,
            SizedBox(
              width: double.infinity,
              height: 50,
              child: MainButton(
                label: _isProcessing ? 'Saving...' : 'Save Card',
                onPress: _isProcessing ? null : _saveCard,
                color: context.cs.primary,
                textColor: context.cs.surface,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
